language: node_js
sudo: required
node_js: stable

env:
  global: # 全局变量，上面的提交到github的命令有用到
    - GH_REF: github.com/humshieh/humshieh.github.io.git
    - secure: 
# secure是自动生成的，执行`travis encrypt 'GH_TOKEN=${your_github_personal_access_token}' --add`

addons: # Travis CI建议加的，自动更新api
  apt:
    update: true

cache:
  directories: 
    - node_modules # 缓存 node_modules

branches:
  only:
    - dev # CI 只针对分支 dev

before_install:
  - npm install -g hexo-cli

install:
  - npm install # 初次安装，在CI环境中，执行安装npm依赖
  - npm install hexo-deployer-git --save

# before_script: 

script:
  - hexo clean
  - hexo generate # 执行 hexo generate，把文章编译到public中

after_script: # 执行script成功后，进入到public，把里面的代码提交到博客的master分支
  - git config user.name "humshieh"
  - git config user.email "humshieh@gmail.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy